const $=s=>document.querySelector(s),{cases,paragraphs}=window.NEWS,steps=[...document.querySelectorAll('.scroll-step')],reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const sceneAssets=["meal","trash","lego","debate","care"];let current=-2,currentPhase=-1,pending=false;
window.SCMP_INTRO="지난 4일 홍콩 사우스차이나모닝포스트(SCMP)에 따르면 중국 젊은층을 중심으로 이 같은 '대행 경제(stand-in economy)'가 확산하고 있습니다. 매체는 \"시간에 쫓기는 소비자들이 일상적인 업무를 직접 처리할 시간이나 인내심, 전문성이 부족해 편의를 위해 기꺼이 비용을 지불하면서 관련 서비스가 인기를 얻고 있다\"고 설명했는데요.";
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function focus(i,phase=0){if(i===current&&phase===currentPhase)return;const changed=i!==current;if(changed&&i>=0){$('#case-art-image').src='assets/case-'+sceneAssets[i]+'.png';$('#case-art-image').alt=cases[i].name+' 대행 사례를 횡단보도 속 인물의 외형에 맞춰 재구성한 AI 연출 장면';}current=i;currentPhase=phase;$('#stage').dataset.scene=i;if(changed){$('#stage').classList.remove('scene-arriving');void $('#stage').offsetWidth;$('#stage').classList.add('scene-arriving');}const card=$('#story-card'),plane=$('#plane'),color=$('#color');card.hidden=i<0&&![-3,-6,-4,-7,-5].includes(i);card.classList.toggle('bridge-card',i===-3||i===-6);$('#stage').classList.toggle('bridge-view',[-3,-6,-4,-7,-5].includes(i));card.classList.toggle('context-card',i===-4||i===-7||i===-5);$('#stage').classList.toggle('quiet-view',i<0);$('#stage').classList.toggle('source-view',i===-4||i===-7);$('#stage').classList.toggle('intro-view',[-3,-6,-4,-7].includes(i));card.classList.toggle('intro-panel',[-3,-6,-4,-7].includes(i));if(i===-3)card.innerHTML='<p class="bridge-list intro-copy">'+esc(window.BRIDGE.split('\n').slice(0,2).join('\n'))+'</p>';if(i===-6)card.innerHTML='<p class="bridge-statement intro-copy">'+esc(window.BRIDGE.split('\n').slice(2).join('\n')).replace('돈만 내면 대신해주는 대행업','<mark>돈만 내면 대신해주는 대행업</mark>')+'</p>';if(i===-4)card.innerHTML='<p class="source-narration intro-copy">'+esc(window.SCMP_INTRO.split(' 매체는 ')[0])+'</p>';if(i===-7)card.innerHTML='<div class="intro-copy"><p class="source-narration">매체는 '+esc(window.SCMP_INTRO.split(' 매체는 ')[1])+'</p></div>';if(i===-5)card.innerHTML='<p class="reenactment-note">기사를 참고해 가상 인물의 상황을 재연해봤습니다.</p><p class="reference-note">SCMP 보도 · 아시아경제 허미담 기자의 10월 6일 기사 참고</p>';plane.classList.toggle('focused',i>=0);color.classList.toggle('active',i>=0);if(i>=0){const c=cases[i],intro=window.INTROS[i];plane.style.setProperty('--x',c.x+'%');plane.style.setProperty('--y',c.y+'%');color.style.setProperty('--x',c.x+'%');color.style.setProperty('--y',c.y+'%');card.innerHTML=phase===0?`<h2 class="thought">${esc('"'+window.CONCERNS[i]+'"')}</h2>`:`<p class="narration">${esc(phase===2?c.desc:intro[1])}</p>`;card.classList.remove('entering');void card.offsetWidth;card.classList.add('entering')}layout()}
function layout(){const stage=$('#stage'),w=stage.clientWidth,h=stage.clientHeight,mobile=w<=800,scale=Math.max(w/1536,h/1024),iw=1536*scale,ih=1024*scale;if(mobile){$('#case-art').style.height=Math.max(140,h-$('#story-card').offsetHeight-52)+'px'}else{$('#case-art').style.height='';}$('#plane').style.width=iw+'px';$('#plane').style.height=ih+'px';let z=1,x=(w-iw)/2,y=(h-ih)/2;if(current>=0){const c=cases[current];z=mobile?1.15:2;x=w*(mobile?.5:.32)-iw*c.x/100*z;y=h*(mobile?.27:.5)-ih*c.y/100*z}$('#plane').style.transform=`translate(${x}px,${y}px) scale(${z})`}
function update(){pending=false;updateEnding();updateClosing();const target=innerHeight*.48;let active=steps[0];for(const step of steps){if(step.getBoundingClientRect().top<=target)active=step;else break}const rect=active.getBoundingClientRect(),part=(target-rect.top)/rect.height;const scene=Number(active.dataset.scene);focus(scene,scene<0?0:part>.62?2:part>.30?1:0);const dailyColor=scene===-4?Math.max(0,Math.min(1,part/.5)):scene===-7?1-Math.max(0,Math.min(1,part/.5)):0;$('#stage').style.setProperty('--daily-color',String(dailyColor));const wash=Math.max(0,Math.min(1,part/.72));$('#stage').style.setProperty('--source-wash',String(wash*wash*(3-2*wash)));$('#stage').classList.toggle('source-quote-view',scene===-7);if([-3,-6,-4,-7].includes(scene)){const enter=Math.max(0,Math.min(1,part/.18)),leave=Math.max(0,Math.min(1,(part-.82)/.18));$('#story-card').style.setProperty('--intro-y',reduced?'0px':((1-enter)-leave)*Math.min(140,innerHeight*.2)+'px');$('#story-card').style.setProperty('--intro-alpha',reduced?'1':String(Math.min(enter,1-leave)));}const reveal=scene>=0?Math.max(0,Math.min(1,(part-.35)/.16)):0;$('#case-art').style.setProperty('--scene-reveal',reduced?'1':String(reveal*reveal*(3-2*reveal)));$('#case-art').dataset.direction=scene%2?'right':'left';const inDetail=scene>=0&&part>.35&&$('#case-art-image').complete&&$('#case-art-image').naturalWidth>0;$('#case-art').setAttribute('aria-hidden',String(!inDetail));$('#case-art').classList.toggle('active',inDetail);$('#case-art').classList.toggle('colorful',inDetail&&part>.46);$('#stage').classList.toggle('detail-view',inDetail);const story=$('.scroll-story').getBoundingClientRect();$('#progress').style.width=Math.max(0,Math.min(100,-story.top/(story.height-innerHeight)*100))+'%'}
function schedule(){if(!pending){pending=true;requestAnimationFrame(update)}}addEventListener('scroll',schedule,{passive:true});addEventListener('resize',()=>{layout();schedule()});new ResizeObserver(layout).observe($('#stage'));new ResizeObserver(layout).observe($('#story-card'));
const endings=[
{title:'돈으로 사는 것은, 시간일까?',body:["전문가들은 이러한 현상을 이른바 ‘게으른 경제(lazy economy)’의 연장선으로 보고 있습니다. 소비자가 돈을 지불해 자신의 시간을 보다 효율적으로 활용하려는 소비 형태라는 설명입니다.","지메이대학교 금융경제학부 리나 부교수는 관련 서비스가 개인의 효율성과 삶의 질을 높이는 동시에 새로운 형태의 일자리를 만들어낼 수 있다고 평가했습니다."],art:0,alt:'이용자의 휴식과 대행자의 요리가 함께 보이는 장면'},
{title:'편리함에는 어떤 대가가 있을까?',body:["다만 문제점도 있습니다. 대부분의 거래가 개인 간 직접 거래 형태로 이뤄지는 만큼 사기나 개인정보 침해 가능성이 있고, 서비스가 기대에 미치지 못했을 때 피해를 구제받기 어렵다는 지적입니다."],art:1,alt:'스마트폰으로 개인 간 거래를 하며 고민하는 이용자'},
{title:'편리함을 넘어, 삶의 경험까지',art:2,body:['대행 경제를 바라보는 누리꾼들의 반응도 엇갈렸습니다. 한 누리꾼은 다음과 같이 말했습니다.'],speaker:'한 누리꾼',quote:'일상의 사소한 일을 돈으로 해결할 수 있게 된다면 우리는 더 큰 자유를 얻는 것일까, 아니면 삶을 직접 경험하는 일부를 조용히 포기하는 것일까',alt:'식탁에서 마주한 젊은 여성과 노인, 그 사이의 빈 의자'}
 ];
function emphasizeEnding(text){let html=esc(text);for(const [phrase,kind] of [['‘게으른 경제(lazy economy)’','economy'],['사기나 개인정보 침해 가능성','risk'],['피해를 구제받기 어렵다','risk'],['우리는 더 큰 자유를 얻는 것일까','freedom'],['삶을 직접 경험하는 일부를 조용히 포기하는 것일까','loss']])html=html.replace(esc(phrase),'<strong class="ending-emphasis '+kind+'">'+esc(phrase)+'</strong>');return html;}
function endingCopy(e,i){return `${e.body.map(p=>'<p>'+emphasizeEnding(p)+'</p>').join('')}${e.quote?'<blockquote>“'+emphasizeEnding(e.quote)+'”</blockquote>':''}`;}
$('#ending-mobile').innerHTML=endings.map((e,i)=>`<article class="mobile-ending-scene"><svg class="mobile-ending-image" viewBox="${e.art*512} 0 512 1024" role="img" aria-label="${esc(e.alt)}"><defs><clipPath id="ending-panel-${i}"><rect x="${e.art*512}" y="0" width="512" height="1024" /></clipPath></defs><image href="assets/ending-triptych.png" width="1536" height="1024" clip-path="url(#ending-panel-${i})" /></svg><div class="ending-card">${endingCopy(e,i)}</div><span class="ai">AI 연출 이미지</span></article>`).join('');
let endingCurrent=-1;const endingSteps=[...document.querySelectorAll('.ending-step')];
function updateEnding(){let i=0;for(const step of endingSteps){if(step.getBoundingClientRect().top<=innerHeight*.48)i=Number(step.dataset.ending)}const activeEnding=endingSteps[i],endingRect=activeEnding.getBoundingClientRect();const reading=Math.max(0,Math.min(1,(innerHeight*.48-endingRect.top)/endingRect.height));$('.ending-stage').style.setProperty('--ending-reading',String(reading));if(i===endingCurrent)return;endingCurrent=i;$('.ending-stage').dataset.ending=i;const e=endings[i];$('#ending-art').innerHTML=`<svg viewBox="${e.art*512} 0 512 1024" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><defs><clipPath id="desktop-ending-panel"><rect x="${e.art*512}" y="0" width="512" height="1024" /></clipPath></defs><image href="assets/ending-triptych.png" width="1536" height="1024" clip-path="url(#desktop-ending-panel)" /></svg>`;$('#ending-art').setAttribute('aria-label',e.alt);$('#ending-card').innerHTML=`${e.body.map(p=>'<p>'+emphasizeEnding(p)+'</p>').join('')}${e.quote?'<blockquote>“'+emphasizeEnding(e.quote)+'”</blockquote>':''}`;for(const node of [$('#ending-art'),$('#ending-card')]){node.classList.remove('ending-arriving');void node.offsetWidth;node.classList.add('ending-arriving');}$('#ending-dots').innerHTML=endings.map((_,n)=>'<i class="'+(n===i?'active':'')+'"></i>').join('');}
const closingSection=$('#closing'),choreLanes=[...document.querySelectorAll('.chore-lane')];
if(!reduced)document.documentElement.classList.add('has-closing-motion');
function updateClosing(){const rect=closingSection.getBoundingClientRect(),travel=Math.max(1,closingSection.offsetHeight-innerHeight),progress=Math.max(0,Math.min(1,-rect.top/travel));closingSection.style.setProperty('--closing-progress',String(progress));const fade=Math.max(0,Math.min(1,(progress-.24)/.52)),reveal=reduced?1:Math.max(0,Math.min(1,(progress-.48)/.24));closingSection.style.setProperty('--closing-fade',String(fade));closingSection.style.setProperty('--closing-reveal',String(reveal));choreLanes.forEach((lane,i)=>{const dir=i%2?-1:1,dx=dir*progress*(42+(i%3)*18),dy=progress*((i%3)-1)*12;lane.style.transform='translate3d('+dx+'px,'+dy+'px,0)';});closingSection.classList.toggle('question-locked',progress>=.7);}
$('#case-art-image').addEventListener('load',schedule);update();



// One entrance per visible block; content stays readable without animation.
if(!reduced){const entranceObserver=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){entry.target.classList.add('flow-arriving');entranceObserver.unobserve(entry.target);}},{threshold:.12});for(const node of document.querySelectorAll('.mobile-ending-scene .ending-card,.mobile-ending-image,.closing h1'))entranceObserver.observe(node);}
